### ISSUE TITLE
Add Signup to the Bondi Surfer on the Bondi Facebook page

### ISSUE THREAD

**Issue by LadySKO** [dominikwilkowski/BSBLSC#1]
requires admin access to the bondi page.

**Comment by dominikwilkowski** [comment]
That's admin login to facebook right?

**Comment by dominikwilkowski** [comment]
Let's keep the issues here only about the website and the surfer

**Comment by LadySKO** [comment]
Hi,

Yes the facebook page
https://www.facebook.com/bondisurfclub/info?tab=overview

I've asked Jacob to make me an admin as I am an editor and only admin can
add a link to campaign

Regards
SKO

On 1 February 2016 at 11:21, Dominik Wilkowski <notifications@github.com>
wrote:

> That's admin login to facebook right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dominikwilkowski/BSBLSC/issues/1#issuecomment-177669514>
> .
>



-- 
LadySKO

Aussie Mobile: +61 416 413 924
Dutch Mobile: +31612 960 400 -svp sms
Skype: skotoole
Tweet: @ladysko

**Comment by LadySKO** [comment]
It is about the website and surfer - it is putting a subscribe button on
the facebook page to drive subscriptions to the surfer.

On 1 February 2016 at 12:36, Siobhan O'Toole <skotoole@gmail.com> wrote:

> Hi,
>
> Yes the facebook page
> https://www.facebook.com/bondisurfclub/info?tab=overview
>
> I've asked Jacob to make me an admin as I am an editor and only admin can
> add a link to campaign
>
> Regards
> SKO
>
> On 1 February 2016 at 11:21, Dominik Wilkowski <notifications@github.com>
> wrote:
>
>> That's admin login to facebook right?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dominikwilkowski/BSBLSC/issues/1#issuecomment-177669514>
>> .
>>
>
>
>
> --
> LadySKO
>
> Aussie Mobile: +61 416 413 924
> Dutch Mobile: +31612 960 400 -svp sms
> Skype: skotoole
> Tweet: @ladysko
>



-- 
LadySKO

Aussie Mobile: +61 416 413 924
Dutch Mobile: +31612 960 400 -svp sms
Skype: skotoole
Tweet: @ladysko

**Comment by dominikwilkowski** [comment]
these issues are for changes to either website or surfer. Everything else would be out of context for others.

**Comment by LadySKO** [comment]
I don't understand - we need to be able to add the social media links to
the digital comms ... so if I can't raise those here where do i raise them
and what do you mean the others?

S

On 1 February 2016 at 12:42, Dominik Wilkowski <notifications@github.com>
wrote:

> these issues are for changes to either website or surfer. Everything else
> would be out of context for others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dominikwilkowski/BSBLSC/issues/1#issuecomment-177692685>
> .
>



-- 
LadySKO

Aussie Mobile: +61 416 413 924
Dutch Mobile: +31612 960 400 -svp sms
Skype: skotoole
Tweet: @ladysko

**Comment by dominikwilkowski** [comment]
I believe you are talking about adding a sign up form to the facebook pages. That would be a change to the facebook page. which has no ties with this repo. As this is an open source theme everyone else that comes by seeking to contribute would not know what's going on here.
