### ISSUE TITLE
Add Sign up to the Bondi Surfer to the bondi surfer (for forwards)

### ISSUE THREAD

**Issue by LadySKO** [dominikwilkowski/BSBLSC#3]

**Comment by dominikwilkowski** [comment]
Not sure what that means. You can't sign up to a newsletter from the very same newsletter.

**Comment by LadySKO** [comment]
Hi,

Give me a chance to respond before you close please.

Allow for the forward of emails and for others to subscribe

currently uge does this  by having a forward button that allows forwards
and given our email is so long then the settings get missed

[image: Inline images 1]

On 1 February 2016 at 12:01, Dominik Wilkowski <notifications@github.com>
wrote:

> Closed #3 <https://github.com/dominikwilkowski/BSBLSC/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dominikwilkowski/BSBLSC/issues/3#event-533486043>.
>



-- 
LadySKO

Aussie Mobile: +61 416 413 924
Dutch Mobile: +31612 960 400 -svp sms
Skype: skotoole
Tweet: @ladysko
