### ISSUE TITLE
Add unsubscribe to bondi Surfer (SPAM LawS)

### ISSUE THREAD

**Issue by LadySKO** [dominikwilkowski/BSBLSC#4]

**Comment by dominikwilkowski** [comment]
Has been in there since version 1
<img width="626" alt="screen shot 2016-02-01 at 11 19 14 am" src="https://cloud.githubusercontent.com/assets/1266923/12706297/ad2f8e96-c8d5-11e5-9155-d3669a7043dc.png">

**Comment by LadySKO** [comment]
Ok thanks

On 1 February 2016 at 11:19, Dominik Wilkowski <notifications@github.com>
wrote:

> Closed #4 <https://github.com/dominikwilkowski/BSBLSC/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dominikwilkowski/BSBLSC/issues/4#event-533465657>.
>



-- 
LadySKO

Aussie Mobile: +61 416 413 924
Dutch Mobile: +31612 960 400 -svp sms
Skype: skotoole
Tweet: @ladysko
